-- DDL DATA DEFINATION LANGUAGE - definição da estrutua de dados
  -- CREATE
  -- DROP
  -- ALTER
-- DML DATA MANIPULATION LANGUAGE - manipulação de dados
  -- INSERT
  -- DELETE
  -- UPDATE
-- DQL DATA QUERY LANGUAGE - consulta de dados
  -- SELECT
-- DTL DATA TRANSACTION LANGUAGE - tranzação de dados
  -- BEGIN TRANSACTION
  -- COMMIT
  -- ROLLBACK
-- DCL DATA CONTROL LANGUAGE - controle de de privilegios do usuario
  -- GRANT
  -- DENY 
  -- REVOKE